version: "3.7"

services:
  ubuntu-base:
    build:
      context: .
      args:
        install_dir: ./install
        set_dir: ./set
        source_dir: ./source
        image_build_dir: ./build/ubuntu-base
      dockerfile: build/ubuntu-base/Dockerfile
    image: "ubuntu-base:latest"
    stdin_open: true
    tty: true

  ansible:
    build:
      context: .
      args:
        install_dir: ./install
        set_dir: ./set
        source_dir: ./source
        image_build_dir: ./build/ansible
      dockerfile: build/ansible/Dockerfile
    image: "ansible:latest"
    stdin_open: true
    tty: true