version: "3.7"

networks:
  default:
    driver: bridge

volumes:
  jenkins_volume:
    external: true

services:
  ubuntu-base:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/ubuntu-base
      dockerfile: builders/ubuntu-base/Dockerfile
    image: "ubuntu-base:latest"
    stdin_open: true
    tty: true

  traefik:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/traefik
        TRAEFIK_VERSION: '2.10.4'
      dockerfile: builders/traefik/Dockerfile
    image: "traefik:latest"
    container_name: traefik
    hostname: traefik
    environment:
      - TRAEFIK_CONFIG=local
      - CERT_CONFIG=local 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)" 
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.priority=1"
    stdin_open: true
    tty: true

  service-deploy:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/service-deploy
        ANSIBLE_VERSION: 2.9
        PYTHON_VERSION: 3.9
        TERRAFORM_VERSION: 1.3.7
      dockerfile: builders/service-deploy/Dockerfile
    image: "service-deploy:latest"
    hostname: service-deploy
    container_name: service-deploy
    stdin_open: true
    tty: true

  jenkins:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/jenkins
        OPEN_JDK_VERSION: 17
        JENKINS_VERSION: 1
      dockerfile: builders/jenkins/Dockerfile
    image: "jenkins:latest"
    hostname: jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_volume:/var/cache/jenkins/war/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.local`)"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    stdin_open: true
    tty: true

  varnish:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/varnish
      dockerfile: builders/varnish/Dockerfile
    image: "varnish:latest"
    environment:
      - VARNISH_CONFIG=default
    stdin_open: true
    tty: true

  rabbitmq:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/rabbitmq
      dockerfile: builders/rabbitmq/Dockerfile
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.dev`)"
#      - "traefik.http.routers.rabbitmq.service=rabbitmq"
#      - "traefik.http.routers.rabbitmq.tls=true"
#      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    stdin_open: true
    tty: true