version: "3.7"

services:
  ubuntu-base:
    build:
      context: .
      args:
        install_dir: ./install
        set_dir: ./set
        source_dir: ./source
        image_build_dir: ./build/ubuntu-base
      dockerfile: build/ubuntu-base/Dockerfile
    image: "ubuntu-base:latest"
    stdin_open: true
    tty: true

  ansible:
    build:
      context: .
      args:
        install_dir: ./install
        set_dir: ./set
        source_dir: ./source
        image_build_dir: ./build/ansible
        ANSIBLE_VERSION: 2.9
        PYTHON_VERSION: 3.10
      dockerfile: build/ansible/Dockerfile
    image: "ansible:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ansible.rule=Host(`ansible.dev`)"
      - "traefik.http.routers.ansible.service=ansible"
      - "traefik.http.routers.ansible.tls=true"
      - "traefik.http.services.ansible.loadbalancer.server.port=80"
    stdin_open: true
    tty: true

  varnish:
    build:
      context: .
      args:
        install_dir: ./install
        set_dir: ./set
        source_dir: ./source
        image_build_dir: ./build/varnish
      dockerfile: build/varnish/Dockerfile
    image: "varnish:latest"
    environment:
      - VARNISH_CONFIG=default
    stdin_open: true
    tty: true

  traefik:
      build:
        context: .
        args:
          install_dir: ./install
          set_dir: ./set
          source_dir: ./source
          image_build_dir: ./build/traefik
          TRAEFIK_VERSION: 2.9.6
        dockerfile: build/traefik/Dockerfile
      image: "traefik:latest"
      environment:
        - TRAEFIK_CONFIG= default
      ports:
        - "80:80"
        - "443:443"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.dev`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.traefik.tls=true"
      stdin_open: true
      tty: true

  zabbix:
    build:
      context: .
      args:
        install_dir: ./install
        set_dir: ./set
        source_dir: ./source
        image_build_dir: ./build/zabbix
        ZABBIX_VERSION: 6.0.4
        MYSQL_VERSION: 7.4
      dockerfile: build/varnish/Dockerfile
    image: "zabbix:latest"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.zabbix.rule=Host(`zabbix.dev`)"
#      - "traefik.http.routers.zabbix.service=zabbix"
#      - "traefik.http.routers.zabbix.tls=true"
#      - "traefik.http.services.zabbix.loadbalancer.server.port=80"
    stdin_open: true
    tty: true

  rabbitmq:
    build:
      context: .
      args:
        install_dir: ./install
        set_dir: ./set
        source_dir: ./source
        image_build_dir: ./build/rabbbitmq
      dockerfile: build/rabbitmq/Dockerfile
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.dev`)"
#      - "traefik.http.routers.rabbitmq.service=rabbitmq"
#      - "traefik.http.routers.rabbitmq.tls=true"
#      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    stdin_open: true
    tty: true