version: "3.7"

networks:
  default:
    driver: bridge

volumes:
  jenkins_volume:
    external: true
  grafana_volume:
    external: true
  prometheus_volume:
    external: true

services:
  ubuntu-base:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/ubuntu-base
      dockerfile: builders/ubuntu-base/Dockerfile
    image: "ubuntu-base:latest"
    stdin_open: true
    tty: true

  traefik:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/traefik
        TRAEFIK_VERSION: '2.10.4'
      dockerfile: builders/traefik/Dockerfile
    image: "traefik:latest"
    container_name: traefik
    hostname: traefik
    environment:
      - TRAEFIK_CONFIG=local
      - CERT_CONFIG=local 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)" 
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.priority=1"
    stdin_open: true
    tty: true

  service-deploy:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/service-deploy
        ANSIBLE_VERSION: 2.9
        PYTHON_VERSION: 3.9
        TERRAFORM_VERSION: 1.3.7
        HELM_VERSION: 3.13.4
      dockerfile: builders/service-deploy/Dockerfile
    image: "service-deploy:latest"
    hostname: service-deploy
    container_name: service-deploy
    stdin_open: true
    tty: true

  jenkins:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/jenkins
        OPEN_JDK_VERSION: 17
        JENKINS_VERSION: 1
      dockerfile: builders/jenkins/Dockerfile
    image: "jenkins:latest"
    hostname: jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_volume:/root/.jenkins
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.local`)"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    stdin_open: true
    tty: true

  grafana:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/grafana
        GRAFANA_VERSION: '10.1.4'
      dockerfile: builders/grafana/Dockerfile
    image: "grafana:latest"
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_volume:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.local`)"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.priority=10"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    stdin_open: true
    tty: true

  prometheus:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/prometheus
        PROMETHEUS_VERSION: 2.47.1
      dockerfile: builders/prometheus/Dockerfile
    image: "prometheus:latest"
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_volume:/etc/prometheus/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.local`)" 
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.priority=10"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    stdin_open: true
    tty: true

  cadvisor:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/cadvisor
        CADVISOR_VERSION: 0.47.2
      dockerfile: builders/cadvisor/Dockerfile
    image: "cadvisor:latest"
    container_name: cadvisor
    hostname: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/machine-id:/etc/machine-id:ro"
      - "/var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro"
      - "/dev/disk/:/dev/disk"
      - "/:/rootfs"
    privileged: true
    devices:
      - "/dev/kmsg"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.local`)"
      - "traefik.http.routers.cadvisor.service=cadvisor"
      - "traefik.http.routers.cadvisor.tls=true"
      - "traefik.http.routers.cadvisor.priority=10"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
    stdin_open: true
    tty: true

  node-exporter:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/node-exporter
        NODE_EXPORTER_VERSION: 1.7.0
      dockerfile: builders/node-exporter/Dockerfile
    image: "node-exporter:latest"
    container_name: node-exporter
    hostname: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - '/:/host:ro,rslave'
    pid: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-exporter.rule=Host(`node-exporter.local`)"
      - "traefik.http.routers.node-exporter.service=node-exporter"
      - "traefik.http.routers.node-exporter.tls=true"
      - "traefik.http.routers.node-exporter.priority=10"
      - "traefik.http.services.node-exporter.loadbalancer.server.port=9100"
    stdin_open: true
    tty: true

  mysql-exporter:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/mysql-exporter
        MYSQL_EXPORTER_VERSION: 0.15.1
      dockerfile: builders/mysql-exporter/Dockerfile
    image: "mysql-exporter:latest"
    container_name: mysql-exporter
    hostname: mysql-exporter
    ports:
      - "9104:9104"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mysql-exporter.rule=Host(`mysql-exporter.local`)" 
      - "traefik.http.routers.mysql-exporter.service=mysql-exporter"
      - "traefik.http.routers.mysql-exporter.tls=true"
      - "traefik.http.routers.mysql-exporter.priority=10"
      - "traefik.http.services.mysql-exporter.loadbalancer.server.port=9104"
    stdin_open: true
    tty: true

  alert-manager:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/alert-manager
        ALERTMANAGER_VERSION: 0.26.0
      dockerfile: builders/alert-manager/Dockerfile
    image: "alert-manager:latest"
    container_name: alert-manager
    hostname: alert-manager
    ports:
      - "9093:9093"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alert-manager.rule=Host(`alert-manager.local`)"
      - "traefik.http.routers.alert-manager.service=alert-manager"
      - "traefik.http.routers.alert-manager.tls=true"
      - "traefik.http.routers.alert-manager.priority=10"
      - "traefik.http.services.alert-manager.loadbalancer.server.port=9093"
    stdin_open: true
    tty: true

  blackbox:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/blackbox
        BLACKBOX_VERSION: 0.24.0
      dockerfile: builders/blackbox/Dockerfile
    image: "blackbox:latest"
    container_name: blackbox
    hostname: blackbox
    ports:
      - "9115:9115"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blackbox.rule=Host(`blackbox.local`)" 
      - "traefik.http.routers.blackbox.service=blackbox"
      - "traefik.http.routers.blackbox.tls=true"
      - "traefik.http.routers.blackbox.priority=10"
      - "traefik.http.services.blackbox.loadbalancer.server.port=9115"
    stdin_open: true
    tty: true

  wazuh-dashboard:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/wazuh-dashboard
        WAZUH_DASHBOARD_VERSION: 4.7
      dockerfile: builders/wazuh-dashboard/Dockerfile
    image: "wazuh-dashboard:latest"
    container_name: wazuh-dashboard
    hostname: wazuh-dashboard
    ports:
      - "443:5601"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wazuh-dashboard.rule=Host(`wazuh-dashboard.local`)"
      - "traefik.http.routers.wazuh-dashboard.service=wazuh-dashboard"
      - "traefik.http.routers.wazuh-dashboard.tls=true"
      - "traefik.http.routers.wazuh-dashboard.priority=10"
      - "traefik.http.services.wazuh-dashboard.loadbalancer.server.port=443"
    stdin_open: true
    tty: true

  wazuh-indexer:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/wazuh-indexer
        WAZUH_DASHBOARD_VERSION: 4.7
      dockerfile: builders/wazuh-indexer/Dockerfile
    image: "wazuh-indexer:latest"
    container_name: wazuh-indexer
    hostname: wazuh-indexer
    ports:
      - "9200:9200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wazuh-indexer.rule=Host(`wazuh-indexer.local`)"
      - "traefik.http.routers.wazuh-indexer.service=wazuh-indexer"
      - "traefik.http.routers.wazuh-indexer.tls=true"
      - "traefik.http.routers.wazuh-indexer.priority=10"
      - "traefik.http.services.wazuh-indexer.loadbalancer.server.port=9200"
    stdin_open: true
    tty: true

  wazuh-server:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/wazuh-server
        WAZUH_SERVER_VERSION: 4.7
      dockerfile: builders/wazuh-server/Dockerfile
    image: "wazuh-server:latest"
    container_name: wazuh-server
    hostname: wazuh-server
    ports:
      - "9200:9200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wazuh-server.rule=Host(`wazuh-server.local`)"
      - "traefik.http.routers.wazuh-server.service=wazuh-server"
      - "traefik.http.routers.wazuh-server.tls=true"
      - "traefik.http.routers.wazuh-server.priority=10"
      - "traefik.http.services.wazuh-server.loadbalancer.server.port=9200"
    stdin_open: true
    tty: true

  varnish:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/varnish
      dockerfile: builders/varnish/Dockerfile
    image: "varnish:latest"
    environment:
      - VARNISH_CONFIG=default
    stdin_open: true
    tty: true

  rabbitmq:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/rabbitmq
      dockerfile: builders/rabbitmq/Dockerfile
    image: "rabbitmq:latest"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.local`)"
      - "traefik.http.routers.rabbitmq.service=rabbitmq"
      - "traefik.http.routers.rabbitmq.tls=true"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    stdin_open: true
    tty: true

  wordpress:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/wordpress
        WORDPRESS_VERSION: 6.4.3
        PHP_VERSION: 8.2
      dockerfile: builders/wordpress/Dockerfile
    image: "wordpress:latest"
    container_name: wordpress
    hostname: wordpress
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.local`)"
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    stdin_open: true
    tty: true

  mysql:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/mysql
        MYSQL_VERSION: 8.29-1
        MYSQL_ROOT_PASS: default
      dockerfile: builders/mysql/Dockerfile
    image: "mysql:latest"
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true