version: "3.8"

networks:
  default-vn:
    external: true

volumes:
  wordpress_volume:
    external: true
  mysql_volume:
    external: true

services:
  ubuntu-base:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/ubuntu-base
      dockerfile: builders/ubuntu-base/Dockerfile
    image: "ubuntu-base:latest"
    stdin_open: true
    tty: true

  traefik:
    build:
      context: .
      args:
        cookbooks_dir: ./cookbooks
        image_builder_dir: ./builders/traefik
        TRAEFIK_VERSION: '2.10.4'
      dockerfile: builders/traefik/Dockerfile
    image: "traefik:latest"
    container_name: traefik
    hostname: traefik
    environment:
      - TRAEFIK_CONFIG=local
      - CERT_CONFIG=local 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)" 
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.priority=1"
    stdin_open: true
    tty: true

  wordpress:
    image: "wordpress:latest"
    container_name: wordpress
    hostname: wordpress
    restart: unless-stopped
    cpu_shares: 128
    mem_limit: 256M 
    networks:
      - default-vn
    ports:
      - "80:80"
      - "443:443"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
#    volumes:
#      - wordpress_volume:/var/www/data/wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.local`)" 
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.priority=10"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
#    depends_on:
#      - mysql
#      - traefik
    stdin_open: true
    tty: true

  mysql:
    image: "mysql:8.0"
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    cpu_shares: 128
    mem_limit: 256M 
    networks:
      - default-vn
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
#    volumes:
#      - mysql_volume:/var/lib/mysql
    depends_on:
      - traefik
    stdin_open: true
    tty: true