global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alert-manager:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "/etc/prometheus/alerts.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
# prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

# node-exporter 
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

# cadvisor 
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

