global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alert-manager:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
- "/etc/prometheus/check-host.yml"
- "/etc/prometheus/check-cert.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
# prometheus
- job_name: "prometheus"
  static_configs:
  - targets: ["prometheus:9090"]

- job_name: 'node-exporter'
  # node-exporter 
  static_configs:
  - targets: ['node-exporter:9100']

- job_name: 'cadvisor'
  # cadvisor 
  static_configs:
  - targets: ['cadvisor:8080']

- job_name: 'alert-manager'
  # alert-manager 
  static_configs:
  - targets: ['alert-manager:9093']

- job_name: 'blackbox'
  # blackbox 
  static_configs:
  - targets: ['blackbox:9115']

- job_name: 'blackbox-scrap'
  # blackbox scrap
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
  - targets:
    - https://traefik.local
    - https://grafana.local
    - https://prometheus.local
    - https://alert-manager.local
    - https://blackbox.local
    - https://cadvisor.local
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115
