# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: true

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    Default: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik/local.yml

# EntryPoints definition
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

# Overwrite Default Certificates
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /opt/certificates/local/local.crt
        keyFile: /opt/certificates/local/local.key

# Log information
#log:
#  level: ERROR  # DEBUG, INFO, WARNING, ERROR, CRITICAL
#  format: common  # common, json, logfmt
#  filePath: /var/log/traefik/traefik.log

# Accesslog
#accesslog:
#  format: common  # common, json, logfmt
#  filePath: /var/log/traefik/access.log